### ISSUE TITLE
Зачем этот jar в папке lib?

### ISSUE THREAD

**Issue by Fodense** [ykatrinka/hw-gradle-task#1]
https://github.com/ykatrinka/hw-gradle-task/blob/c10ba44852bf36f259f4a4b0cf6095db5be5d676/gradle-task-core/build.gradle#L14

**Comment by ykv-j** [comment]
У меня jar публикует utils в локальный репозиторий maven. Соответственно нет уверенности, что сработает на другом компьютере. А так есть возможность скопировать.
